### ISSUE TITLE
Query to IEEE database query returns zero results

### ISSUE THREAD

**Issue by ZeroCommits** [jonatasgrosman/findpapers#1]
#### Issue description
Queries to IEEE return zero results

#### Steps to reproduce the issue

1. Install using `pip install findpapers` inside conda environment, python version 3.9.12
2. Install MSVC Build Tools 2022. See screenshot below
3. ~~[Downgrade click to 8.0.4](https://github.com/tiangolo/typer/issues/377#issuecomment-1081705825)~~
4. Enable python environment, execute `findpapers search search.json -q "([artificial intelligence])" --databases "ieee" --token-ieee "mytoken" --token-scopus "mytoken" --limit 30`

#### What's the expected result?
I should see papers from IEEE

#### What's the actual result?
Please see screenshot below

#### Additional details / screenshot
![image](https://user-images.githubusercontent.com/37379471/165349647-fc3e1068-73da-4c1a-982a-d2619be6b038.png)

![image](https://user-images.githubusercontent.com/37379471/165350062-274a78ee-ab4e-4d1b-bab2-8493069bbb2c.png)

**Comment by ZeroCommits** [comment]
Please ignore item 3 above. This is because of a conflict with dependencies with having Spyder installed on the same environment.

**Comment by jonatasgrosman** [comment]
Hi @ZeroCommits, I couldn't reproduce your error. I think that maybe your IEEE token is invalid.
Can you use the --verbose argument and post the output log here?

**Comment by ZeroCommits** [comment]
Hello @jonatasgrosman, please see the attached text files. Another issue happens (see debug-noscopustoken.txt) when I do not put my scopus token even though I am just using IEEE.
[debug.txt](https://github.com/jonatasgrosman/findpapers/files/8992576/debug.txt)
[debug-noscopustoken.txt](https://github.com/jonatasgrosman/findpapers/files/8992577/debug-noscopustoken.txt)

**Comment by jonatasgrosman** [comment]
Hi @ZeroCommits! In your logs, I could see a lot of HTTP 403 errors happening. This HTTP code error is related to authorization issues. Try to generate new authorization tokens for Scopus and IEEE. For some reason, the ones you're using are probably invalid :(

**Comment by ZeroCommits** [comment]
Thanks for looking into this. I tried using the Dynamic Query Tool from the IEEE developer website with new API keys and also getting the HTTP 403 errors there. Registered for a new account and also getting the same error. Already asked support to look into this issue and will update this thread once I get a response.

**Comment by ZeroCommits** [comment]
Fixed after renewing API keys.
