### ISSUE TITLE
Searching on ACM database freezes.

### ISSUE THREAD

**Issue by iannunes** [jonatasgrosman/findpapers#3]
Regardless the query, when the fetching process is almost ending it freezes. 

An example of query follows.

([openset] OR [open-set] OR [open set])

AND

([recognition] OR [classification] OR [segmentation] OR [semantic segmentation])

AND

([deep learning] OR [neural network])

AND NOT

([voice] OR [music] or [speech])

**Comment by jonatasgrosman** [comment]
fixed by https://github.com/jonatasgrosman/findpapers/commit/6569958047d61362a28eb95e3a08f8e5f2603cc6
